#!/bin/bash

#; ______________
#; |  \o| . ||__   https://youtube.com/@diws
#; |__/||_|_| __|  https://github.com/diws1
#;


# List of command
name=$(whoami)
os=$(source /etc/os-release && echo $PRETTY_NAME)
kernel=$(uname -sr)
shell=$(basename $SHELL)
uptime=$(uptime -p | sed 's/up //')
wm=$(echo $DESKTOP_SESSION)
mem=$(free -h | awk 'NR==2{print $3}' | sed s/i//)
free=$(free -h | awk 'NR==2{print $4}' | sed s/i//)

# List colors
#normal
bla=$(tput setaf 0)
red=$(tput setaf 1)
gre=$(tput setaf 2)
yel=$(tput setaf 3)
blu=$(tput setaf 4)
mag=$(tput setaf 5)
cya=$(tput setaf 6)
whi=$(tput setaf 7)
#bright
bbla=$(tput setaf 8)
bred=$(tput setaf 9)
bgre=$(tput setaf 10)
byel=$(tput setaf 11)
bblu=$(tput setaf 12)
bmag=$(tput setaf 13)
bcya=$(tput setaf 14)
bwhi=$(tput setaf 15)

# Other variable (bold, reset)
bld=$(tput bold)
rst=$(tput sgr0)

# Color output
co=$(
	color () {
        	for c; do
                	printf '\e[48;5;%dm%03d' $c $c
        	done
        	printf '\e[0m \n'
	}

	IFS=$' \t\n'
	color {0..7}
)

# Print result
cat <<EOF

${mag}     ██         ██	${rst}${blu}${bld} usr ${rst} ${name}
${mag}       ██     ██     	${rst}${gre}${bld} dis ${rst} ${os}
${mag}     ████████████   	${rst}${mag}${bld} knl ${rst} ${kernel}
${mag} ██ ███ .█████ .██	${rst}${whi}${bld} sh  ${rst} ${shell}
${mag} ███████████████████	${rst}${red}${bld} up  ${rst} ${uptime}
${mag}     █████  █████ ██	${rst}${cya}${bld} wm  ${rst} ${wm}
${mag}       ▀▀▀▀▀▀▀▀		${rst}${yel}${bld} mem ${rst} ${mem}

EOF

