#!/bin/bash

# arch logo
col=$(tput setaf 12)
rst=$(tput sgr0)
s=$(echo "\\") #backslash

cat <<EOF
$col
        /'
       /  $s
       \   $s
     /'    "$s
    /   ..   $s
   /  _"  '_, $s
  , /        $s ;
$rst
EOF
