#!/bin/bash

# artix logo
col=$(tput setaf 12)
rst=$(tput sgr0)
s=$(echo "\\") #backslash

cat <<EOF
$col
        /'
       /  $s
      '-_  $s
     /'-."-_$s
    /    '.-~
   / _.-"^_.-'$s
  /,"       '~.$s
$rst
EOF

