#!/bin/bash

# majaro logo
col=$(tput setaf 2)
bld=$(tput bold)
rev=$(tput rev)
rst=$(tput sgr0)

cat <<EOF
$col$bld
      _______ ___
     /  ____//  /
    /  //  //  /
   /  //  //  /
  /__//__//__/

    $rev manjaro 
$rst
EOF

