#!/bin/bash

# solus logo
col1=$(tput setaf 15)
col2=$(tput setaf 8)
col3=$(tput setaf 12)
rst=$(tput sgr0)

cat <<EOF
$col1
     .
     /\  .  ,
    /  | |\.\'.
  .'.__|/_." -^$col2/__
$col2   "-=======^^'
$col3  ~~______~~~~~-
    - ~~~~~~~'
$rst
EOF


#     .
#     /\  .  ,
#    /  | |\.\'.
#  .'.__|/_." -^/__
#   "-=======^^'
#  ~~______~~~~~-
#    - ~~~~~~~'

