#!/bin/bash

# void logo
col=$(tput setaf 10)
rst=$(tput sgr0)

cat <<EOF
$col
       ,  -----  ,
    ,'     ___    ".
   _  __ ,___ :_ ___
  / \/ // . // // , /
  \__.//___//_//__ /
   ^.   '--- "    *
     "  _____ - '
$rst
EOF
