#!/bin/bash

# List of command
name=$(whoami)
os=$(source /etc/os-release && echo $PRETTY_NAME | awk '{print$1}')
kernel=$(uname -sr | awk '{print$1}')
shell=$(basename $SHELL)
uptime=$(uptime -p | sed 's/up //')
wm=$(echo $DESKTOP_SESSION)
mem=$(free -h | awk 'NR==2{print $3}' | sed s/i//)
free=$(free -h | awk 'NR==2{print $4}' | sed s/i//)

# Variabels
bld=$(tput bold)
rst=$(tput sgr0)

# List of colors
bla=$(tput setaf 0)
red=$(tput setaf 1)
gre=$(tput setaf 2)
yel=$(tput setaf 3)
blu=$(tput setaf 4)
mag=$(tput setaf 5)
cya=$(tput setaf 6)
whi=$(tput setaf 7)
bbla=$(tput setaf 8)
bred=$(tput setaf 9)
bgre=$(tput setaf 10)
byel=$(tput setaf 11)
bblu=$(tput setaf 12)
bmag=$(tput setaf 13)
bcya=$(tput setaf 14)
bwhi=$(tput setaf 15)

# Color output
co=$(
	color () {
        	for c; do
                	printf '\e[48;5;%dm%03d' $c $c
        	done
        	printf '\e[0m \n'
	}

	IFS=$' \t\n'
	color {0..7}
)

# Print result
cat <<EOF

${bld}       OS ${rst}: ${os}
${bld}   KERNEL ${rst}: ${kernel}
${bld}   UPTIME ${rst}: ${uptime}
${bld}    DE/WM ${rst}: ${wm}
${bld}   MEMORY ${rst}: ${mem}

   ${bla}■ ${red}■ ${gre}■ ${yel}■ ${blu}■ ${mag}■ ${cya}■ ${whi}■${rst}

EOF

